name: pavilion_rewards
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_credit_card: ^3.0.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Manrope_Regular
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf

    - family: Manrope_Bold
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf

    - family: Manrope_ExtraBold
      fonts:
        - asset: assets/fonts/Manrope-ExtraBold.ttf
